### ISSUE TITLE
Cannot authorize with Ecobee

### ISSUE THREAD

**Issue by blerrgh** [ziebelje/beestat-issues#106]
Clicking the "ecobee" button on the beestat homepage displays the following result:

![Capture](https://user-images.githubusercontent.com/41206759/56855290-82ac8300-68f9-11e9-8848-ddafa9088932.PNG)

**Comment by ziebelje** [comment]
Hi!

This typically happens if you are already logged in to ecobee.com when trying to authorize with beestat. The same thing happens when authorizing other services like Google or IFTTT.

The solution is to make sure you are completely logged out of ecobee.com, then you should be able to properly authorize beestat.

Please let me know if that gives you any problems. Thanks!
