### ISSUE TITLE
infinite updating data and when reauthenticating database error

### ISSUE THREAD

**Issue by InternalResponse** [ziebelje/beestat-issues#45]
I get an error on reauthentication 

{"success":false,"data":{"error_message":"Database query failed.","error_code":1206}}

**Comment by ziebelje** [comment]
That particular issue was caused by a database operation that was running (unsuccessfully) overnight. 

> The total number of locks exceeds the lock table size

However, I see another error related to ecobee not authorizing which I am investigating now.

**Comment by ziebelje** [comment]
Scratch that, the other error is related to session expiration. You may be able to get this to work if you fully clear your browser cache, then visit beestat.io and re-authorize ecobee. I'm investigating the issue in the meantime.

**Comment by ziebelje** [comment]
I have found several situations where users seem to get stuck in a loop where it attempts to show their dashboard but they instantly get hit with a "session expired", which sends them to the home page, but then they get sent back to the dashboard because a session was detected...

I have not yet been able to reproduce this issue. @InternalResponse, if you experience this it would be awesome if you could give any additional feedback about how you typically use beestat. For example, is this the first time you've been back in a while or do you use it daily? Have you revoked beestat's access from the ecobee website? Etc.

I'll continue to try and reproduce.
